name: NCCL issue or bug
description: Report an issue or failure when running NCCL code
title: "[Issue]: "
labels: ["triage"]

body:
  - type: markdown
    attributes:
      value: |
        Before reporting a new issue, please search for the behavior in the existing issues. If you found an issue and it is already closed, open a new issue and reference the old one from it.
        
        ---
        
        To address this issue we need some additional information:
  - type: dropdown
    id: type
    attributes:
      label: Issue severity
      description: How is your workload impacted by this issue?
      options:
        - Lower performance than expected
        - Application crash
        - Data corruption
        - Application hang
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Debug Log Files
      description: |
        Please attach NCCL info logs (rerun workload after setting export `NCCL_DEBUG=INFO` and `NCCL_DEBUG_FILE=ncclDebug.%h.%p` to produce one file per rank).

  - type: textarea
    id: repro
    attributes:
      label: Minimal reproducer and steps
      description: |
        * Which steps are necessary to reproduce this error? See [Minimal Bug Reports](https://matthewrocklin.com/minimal-bug-reports) for reference.
        * Include all relevant software versions and environment variables.
        * Is this an intermittent issue? If it is, how frequently does it happen?
        * Is there a previous passing setup, e.g. older NCCL version?

        The easier we can reproduce on our side the more likely we are to be able to solve it in a timely manner.

  - type: input
    id: nccl_version
    attributes:
      label: NCCL Version
      description: |
        NCCL reports its version string in the debug logs.
        You can also determine the version if you know which library was used by running `strings libnccl.so | grep 'NCCL version'`.
      placeholder: "e.g. 2.27.1+cuda12.8"
    validations:
      required: true

  - type: textarea
    id: platform
    attributes:
      label: Which platform are you using?
      description: |
        * Which GPU architecture, network hardware and topology are you using (reported by e.g. `nvidia-smi`, `nvidia-smi topo -m`, `ibstatus`)?
        * Are you running on bare-metal, containers, and/or in the cloud?
        * Does this issue occur at a specific rank/node count?

  - type: textarea
    id: issue-description
    attributes:
      label: Error Message
      description: |
        * What was the first error message in the logs (usually this line includes `NCCL WARN`)?
        * What is the expected vs. observed behavior?


