name: NCCL issue or bug
description: Report an issue or failure when running NCCL code
title: "[Issue]: "
labels: ["triage"]

body:
  - type: markdown
    attributes:
      value: |
        Before reporting a new issue, please search for the behaviour in the existing issues.
        
        ---
        
        To address this issue we need some additional information:
  - type: input
    id: nccl_version
    attributes:
      label: NCCL Version
      description: |
        NCCL reports its version string in the debug logs.
        You can also determine the version if you know which library was used by running `strings libnccl.so | grep 'NCCL version'`.
      placeholder: "e.g. 2.27.1+cuda12.8"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue severity
      description: How is your workload impacted by this issue?
      options:
        - Lower performance than expected
        - Application crash
        - Data corruption
        - Application hang
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Error Message
      description: |
        * What was the first error message in the logs?
        * What is the expected vs. observed behaviour?
    validations:
      required: true

  - type: textarea
    id: platform
    attributes:
      label: Which platform are you using?
      description: |
        * Which GPU architecture, network hardware and topology are you using?
        * Does this issue occur at a specific rank/node count?

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: |
        * Which steps do we need to take to reproduce this error? Please include all relevant software version numbers.
        * Is this an intermittent issue? If it is, how frequently does it happen?
        * Is there a previous passing setup, e.g. older NCCL version?

        The easier we can reproduce on our side the more likely we are to be able to solve it in a timely manner.

  - type: textarea
    id: log
    attributes:
      label: Debug Log Files
      description: |
        Please attach NCCL info logs (rerun workload after setting export NCCL_DEBUG=INFO and NCCL_DEBUG_FILE=ncclDebug.%h.%p to produce one file per rank).
