name: NCCL question
description: Question
title: "[Question]: "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Before reporting a new issue, please search for the behaviour in the existing issues.
        
        ---
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Please conduct the [NCCL UserGuide](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/index.html) before submitting questions here.
    validations:
      required: true
