name: NCCL question
description: Ask the NCCL team a question
title: "[Question]: "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Please consult the [NCCL UserGuide](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/index.html) before submitting questions here.
        ---
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
