name: NCCL request for enhancement
description: Request for enhancement
title: "[RFE]: "
labels: ["enhacement"]

body:
  - type: markdown
    attributes:
      value: |
        Before reporting a new issue, please search for the behaviour in the existing issues.
        
        ---
  - type: textarea
    id: rfe-description
    attributes:
      label: Describe suggested feature
      description: Describe which feature you would like and how NCCL users will benefit from it.
    validations:
      required: true
