name: NCCL request for enhancement
description: Request for enhancement
title: "[RFE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a new RFE, please search for the request in the existing issues.
        
        ---
  - type: textarea
    id: rfe-description
    attributes:
      label: Please provide the below details to support a quick triage.
      description: |
        * What is the goal of this request?
        * Who will benefit from this feature?
        * Is this request for a specific GPU architecture or network infrastructure?
        * How will this feature improve current workflows or processes?
        * What is the priority level of this request?
